name: Submit Application

on:
  push:
    branches:
      - main

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Submit application
        env:
          SIGNING_SECRET: ${{ secrets.SIGNING_SECRET }}
          ACTION_RUN_LINK: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        run: python submit.py
